description = "Support for Wiki Entities"
name = "wikiada_support"
version = "1.4.2"
licenses = "Apache-2.0"
authors = ["Stephane.Carrez@gmail.com"]
maintainers = ["Stephane.Carrez@gmail.com"]
maintainers-logins = ["stcarrez"]
project-files = ["support.gpr"]

[[depends-on]]
utilada = "^2.5.0"

[configuration]
disabled = true
