--  Generated by gen-ada-entities.pl latin1.ent symbol.ent special.ent
private package Wiki.Parsers.Html.Entities is

   pragma Preelaborate;

   AELIG_NAME    : aliased constant String := "AElig";
   AACUTE_NAME   : aliased constant String := "Aacute";
   ACIRC_NAME    : aliased constant String := "Acirc";
   AGRAVE_NAME   : aliased constant String := "Agrave";
   ALPHA_NAME    : aliased constant String := "Alpha";
   ARING_NAME    : aliased constant String := "Aring";
   ATILDE_NAME   : aliased constant String := "Atilde";
   AUML_NAME     : aliased constant String := "Auml";
   BETA_NAME     : aliased constant String := "Beta";
   CCEDIL_NAME   : aliased constant String := "Ccedil";
   CHI_NAME      : aliased constant String := "Chi";
   DAGGER_NAME   : aliased constant String := "Dagger";
   DELTA_NAME    : aliased constant String := "Delta";
   ETH_NAME      : aliased constant String := "ETH";
   EACUTE_NAME   : aliased constant String := "Eacute";
   ECIRC_NAME    : aliased constant String := "Ecirc";
   EGRAVE_NAME   : aliased constant String := "Egrave";
   EPSILON_NAME  : aliased constant String := "Epsilon";
   ETA_NAME      : aliased constant String := "Eta";
   EUML_NAME     : aliased constant String := "Euml";
   GAMMA_NAME    : aliased constant String := "Gamma";
   IACUTE_NAME   : aliased constant String := "Iacute";
   ICIRC_NAME    : aliased constant String := "Icirc";
   IGRAVE_NAME   : aliased constant String := "Igrave";
   IOTA_NAME     : aliased constant String := "Iota";
   IUML_NAME     : aliased constant String := "Iuml";
   KAPPA_NAME    : aliased constant String := "Kappa";
   LAMBDA_NAME   : aliased constant String := "Lambda";
   MU_NAME       : aliased constant String := "Mu";
   NTILDE_NAME   : aliased constant String := "Ntilde";
   NU_NAME       : aliased constant String := "Nu";
   OELIG_NAME    : aliased constant String := "OElig";
   OACUTE_NAME   : aliased constant String := "Oacute";
   OCIRC_NAME    : aliased constant String := "Ocirc";
   OGRAVE_NAME   : aliased constant String := "Ograve";
   OMEGA_NAME    : aliased constant String := "Omega";
   OMICRON_NAME  : aliased constant String := "Omicron";
   OSLASH_NAME   : aliased constant String := "Oslash";
   OTILDE_NAME   : aliased constant String := "Otilde";
   OUML_NAME     : aliased constant String := "Ouml";
   PHI_NAME      : aliased constant String := "Phi";
   PI_NAME       : aliased constant String := "Pi";
   PRIME_NAME    : aliased constant String := "Prime";
   PSI_NAME      : aliased constant String := "Psi";
   RHO_NAME      : aliased constant String := "Rho";
   SCARON_NAME   : aliased constant String := "Scaron";
   SIGMA_NAME    : aliased constant String := "Sigma";
   THORN_NAME    : aliased constant String := "THORN";
   TAU_NAME      : aliased constant String := "Tau";
   THETA_NAME    : aliased constant String := "Theta";
   UACUTE_NAME   : aliased constant String := "Uacute";
   UCIRC_NAME    : aliased constant String := "Ucirc";
   UGRAVE_NAME   : aliased constant String := "Ugrave";
   UPSILON_NAME  : aliased constant String := "Upsilon";
   UUML_NAME     : aliased constant String := "Uuml";
   XI_NAME       : aliased constant String := "Xi";
   YACUTE_NAME   : aliased constant String := "Yacute";
   YUML_NAME     : aliased constant String := "Yuml";
   ZETA_NAME     : aliased constant String := "Zeta";
   N59_NAME      : aliased constant String := "aacute";
   N60_NAME      : aliased constant String := "acirc";
   ACUTE_NAME    : aliased constant String := "acute";
   N62_NAME      : aliased constant String := "aelig";
   N63_NAME      : aliased constant String := "agrave";
   ALEFSYM_NAME  : aliased constant String := "alefsym";
   N65_NAME      : aliased constant String := "alpha";
   AMP_NAME      : aliased constant String := "amp";
   AND_NAME      : aliased constant String := "and";
   ANG_NAME      : aliased constant String := "ang";
   APOS_NAME     : aliased constant String := "apos";
   N70_NAME      : aliased constant String := "aring";
   ASYMP_NAME    : aliased constant String := "asymp";
   N72_NAME      : aliased constant String := "atilde";
   N73_NAME      : aliased constant String := "auml";
   BDQUO_NAME    : aliased constant String := "bdquo";
   N75_NAME      : aliased constant String := "beta";
   BRVBAR_NAME   : aliased constant String := "brvbar";
   BULL_NAME     : aliased constant String := "bull";
   CAP_NAME      : aliased constant String := "cap";
   N79_NAME      : aliased constant String := "ccedil";
   CEDIL_NAME    : aliased constant String := "cedil";
   CENT_NAME     : aliased constant String := "cent";
   N82_NAME      : aliased constant String := "chi";
   CIRC_NAME     : aliased constant String := "circ";
   CLUBS_NAME    : aliased constant String := "clubs";
   CONG_NAME     : aliased constant String := "cong";
   COPY_NAME     : aliased constant String := "copy";
   CRARR_NAME    : aliased constant String := "crarr";
   CUP_NAME      : aliased constant String := "cup";
   CURREN_NAME   : aliased constant String := "curren";
   DARR_NAME     : aliased constant String := "dArr";
   N91_NAME      : aliased constant String := "dagger";
   N92_NAME      : aliased constant String := "darr";
   DEG_NAME      : aliased constant String := "deg";
   N94_NAME      : aliased constant String := "delta";
   DIAMS_NAME    : aliased constant String := "diams";
   DIVIDE_NAME   : aliased constant String := "divide";
   N97_NAME      : aliased constant String := "eacute";
   N98_NAME      : aliased constant String := "ecirc";
   N99_NAME      : aliased constant String := "egrave";
   EMPTY_NAME    : aliased constant String := "empty";
   EMSP_NAME     : aliased constant String := "emsp";
   ENSP_NAME     : aliased constant String := "ensp";
   N103_NAME     : aliased constant String := "epsilon";
   EQUIV_NAME    : aliased constant String := "equiv";
   N105_NAME     : aliased constant String := "eta";
   N106_NAME     : aliased constant String := "eth";
   N107_NAME     : aliased constant String := "euml";
   EURO_NAME     : aliased constant String := "euro";
   EXIST_NAME    : aliased constant String := "exist";
   FNOF_NAME     : aliased constant String := "fnof";
   FORALL_NAME   : aliased constant String := "forall";
   FRAC12_NAME   : aliased constant String := "frac12";
   FRAC14_NAME   : aliased constant String := "frac14";
   FRAC34_NAME   : aliased constant String := "frac34";
   FRASL_NAME    : aliased constant String := "frasl";
   N116_NAME     : aliased constant String := "gamma";
   GE_NAME       : aliased constant String := "ge";
   GT_NAME       : aliased constant String := "gt";
   HARR_NAME     : aliased constant String := "hArr";
   N120_NAME     : aliased constant String := "harr";
   HEARTS_NAME   : aliased constant String := "hearts";
   HELLIP_NAME   : aliased constant String := "hellip";
   N123_NAME     : aliased constant String := "iacute";
   N124_NAME     : aliased constant String := "icirc";
   IEXCL_NAME    : aliased constant String := "iexcl";
   N126_NAME     : aliased constant String := "igrave";
   IMAGE_NAME    : aliased constant String := "image";
   INFIN_NAME    : aliased constant String := "infin";
   INT_NAME      : aliased constant String := "int";
   N130_NAME     : aliased constant String := "iota";
   IQUEST_NAME   : aliased constant String := "iquest";
   ISIN_NAME     : aliased constant String := "isin";
   N133_NAME     : aliased constant String := "iuml";
   N134_NAME     : aliased constant String := "kappa";
   LARR_NAME     : aliased constant String := "lArr";
   N136_NAME     : aliased constant String := "lambda";
   LANG_NAME     : aliased constant String := "lang";
   LAQUO_NAME    : aliased constant String := "laquo";
   N139_NAME     : aliased constant String := "larr";
   LCEIL_NAME    : aliased constant String := "lceil";
   LDQUO_NAME    : aliased constant String := "ldquo";
   LE_NAME       : aliased constant String := "le";
   LFLOOR_NAME   : aliased constant String := "lfloor";
   LOWAST_NAME   : aliased constant String := "lowast";
   LOZ_NAME      : aliased constant String := "loz";
   LRM_NAME      : aliased constant String := "lrm";
   LSAQUO_NAME   : aliased constant String := "lsaquo";
   LSQUO_NAME    : aliased constant String := "lsquo";
   LT_NAME       : aliased constant String := "lt";
   MACR_NAME     : aliased constant String := "macr";
   MDASH_NAME    : aliased constant String := "mdash";
   MICRO_NAME    : aliased constant String := "micro";
   MIDDOT_NAME   : aliased constant String := "middot";
   MINUS_NAME    : aliased constant String := "minus";
   N155_NAME     : aliased constant String := "mu";
   NABLA_NAME    : aliased constant String := "nabla";
   NBSP_NAME     : aliased constant String := "nbsp";
   NDASH_NAME    : aliased constant String := "ndash";
   NE_NAME       : aliased constant String := "ne";
   NI_NAME       : aliased constant String := "ni";
   NOT_NAME      : aliased constant String := "not";
   NOTIN_NAME    : aliased constant String := "notin";
   NSUB_NAME     : aliased constant String := "nsub";
   N164_NAME     : aliased constant String := "ntilde";
   N165_NAME     : aliased constant String := "nu";
   N166_NAME     : aliased constant String := "oacute";
   N167_NAME     : aliased constant String := "ocirc";
   N168_NAME     : aliased constant String := "oelig";
   N169_NAME     : aliased constant String := "ograve";
   OLINE_NAME    : aliased constant String := "oline";
   N171_NAME     : aliased constant String := "omega";
   N172_NAME     : aliased constant String := "omicron";
   OPLUS_NAME    : aliased constant String := "oplus";
   OR_NAME       : aliased constant String := "or";
   ORDF_NAME     : aliased constant String := "ordf";
   ORDM_NAME     : aliased constant String := "ordm";
   N177_NAME     : aliased constant String := "oslash";
   N178_NAME     : aliased constant String := "otilde";
   OTIMES_NAME   : aliased constant String := "otimes";
   N180_NAME     : aliased constant String := "ouml";
   PARA_NAME     : aliased constant String := "para";
   PART_NAME     : aliased constant String := "part";
   PERMIL_NAME   : aliased constant String := "permil";
   PERP_NAME     : aliased constant String := "perp";
   N185_NAME     : aliased constant String := "phi";
   N186_NAME     : aliased constant String := "pi";
   PIV_NAME      : aliased constant String := "piv";
   PLUSMN_NAME   : aliased constant String := "plusmn";
   POUND_NAME    : aliased constant String := "pound";
   N190_NAME     : aliased constant String := "prime";
   PROD_NAME     : aliased constant String := "prod";
   PROP_NAME     : aliased constant String := "prop";
   N193_NAME     : aliased constant String := "psi";
   QUOT_NAME     : aliased constant String := "quot";
   RARR_NAME     : aliased constant String := "rArr";
   RADIC_NAME    : aliased constant String := "radic";
   RANG_NAME     : aliased constant String := "rang";
   RAQUO_NAME    : aliased constant String := "raquo";
   N199_NAME     : aliased constant String := "rarr";
   RCEIL_NAME    : aliased constant String := "rceil";
   RDQUO_NAME    : aliased constant String := "rdquo";
   REAL_NAME     : aliased constant String := "real";
   REG_NAME      : aliased constant String := "reg";
   RFLOOR_NAME   : aliased constant String := "rfloor";
   N205_NAME     : aliased constant String := "rho";
   RLM_NAME      : aliased constant String := "rlm";
   RSAQUO_NAME   : aliased constant String := "rsaquo";
   RSQUO_NAME    : aliased constant String := "rsquo";
   SBQUO_NAME    : aliased constant String := "sbquo";
   N210_NAME     : aliased constant String := "scaron";
   SDOT_NAME     : aliased constant String := "sdot";
   SECT_NAME     : aliased constant String := "sect";
   SHY_NAME      : aliased constant String := "shy";
   N214_NAME     : aliased constant String := "sigma";
   SIGMAF_NAME   : aliased constant String := "sigmaf";
   SIM_NAME      : aliased constant String := "sim";
   SPADES_NAME   : aliased constant String := "spades";
   SUB_NAME      : aliased constant String := "sub";
   SUBE_NAME     : aliased constant String := "sube";
   SUM_NAME      : aliased constant String := "sum";
   SUP_NAME      : aliased constant String := "sup";
   SUP1_NAME     : aliased constant String := "sup1";
   SUP2_NAME     : aliased constant String := "sup2";
   SUP3_NAME     : aliased constant String := "sup3";
   SUPE_NAME     : aliased constant String := "supe";
   SZLIG_NAME    : aliased constant String := "szlig";
   N227_NAME     : aliased constant String := "tau";
   THERE4_NAME   : aliased constant String := "there4";
   N229_NAME     : aliased constant String := "theta";
   THETASYM_NAME : aliased constant String := "thetasym";
   THINSP_NAME   : aliased constant String := "thinsp";
   N232_NAME     : aliased constant String := "thorn";
   TILDE_NAME    : aliased constant String := "tilde";
   TIMES_NAME    : aliased constant String := "times";
   TRADE_NAME    : aliased constant String := "trade";
   UARR_NAME     : aliased constant String := "uArr";
   N237_NAME     : aliased constant String := "uacute";
   N238_NAME     : aliased constant String := "uarr";
   N239_NAME     : aliased constant String := "ucirc";
   N240_NAME     : aliased constant String := "ugrave";
   UML_NAME      : aliased constant String := "uml";
   UPSIH_NAME    : aliased constant String := "upsih";
   N243_NAME     : aliased constant String := "upsilon";
   N244_NAME     : aliased constant String := "uuml";
   WEIERP_NAME   : aliased constant String := "weierp";
   N246_NAME     : aliased constant String := "xi";
   N247_NAME     : aliased constant String := "yacute";
   YEN_NAME      : aliased constant String := "yen";
   N249_NAME     : aliased constant String := "yuml";
   N250_NAME     : aliased constant String := "zeta";
   ZWJ_NAME      : aliased constant String := "zwj";
   ZWNJ_NAME     : aliased constant String := "zwnj";

   type String_Access is access constant String;
   type Keyword_Array is array (Positive range 1 .. 253) of String_Access;
   type Char_Array is array (Positive range 1 .. 253) of Wide_Wide_Character;

   Keywords : constant Keyword_Array := (
      AELIG_NAME'Access,
      AACUTE_NAME'Access,
      ACIRC_NAME'Access,
      AGRAVE_NAME'Access,
      ALPHA_NAME'Access,
      ARING_NAME'Access,
      ATILDE_NAME'Access,
      AUML_NAME'Access,
      BETA_NAME'Access,
      CCEDIL_NAME'Access,
      CHI_NAME'Access,
      DAGGER_NAME'Access,
      DELTA_NAME'Access,
      ETH_NAME'Access,
      EACUTE_NAME'Access,
      ECIRC_NAME'Access,
      EGRAVE_NAME'Access,
      EPSILON_NAME'Access,
      ETA_NAME'Access,
      EUML_NAME'Access,
      GAMMA_NAME'Access,
      IACUTE_NAME'Access,
      ICIRC_NAME'Access,
      IGRAVE_NAME'Access,
      IOTA_NAME'Access,
      IUML_NAME'Access,
      KAPPA_NAME'Access,
      LAMBDA_NAME'Access,
      MU_NAME'Access,
      NTILDE_NAME'Access,
      NU_NAME'Access,
      OELIG_NAME'Access,
      OACUTE_NAME'Access,
      OCIRC_NAME'Access,
      OGRAVE_NAME'Access,
      OMEGA_NAME'Access,
      OMICRON_NAME'Access,
      OSLASH_NAME'Access,
      OTILDE_NAME'Access,
      OUML_NAME'Access,
      PHI_NAME'Access,
      PI_NAME'Access,
      PRIME_NAME'Access,
      PSI_NAME'Access,
      RHO_NAME'Access,
      SCARON_NAME'Access,
      SIGMA_NAME'Access,
      THORN_NAME'Access,
      TAU_NAME'Access,
      THETA_NAME'Access,
      UACUTE_NAME'Access,
      UCIRC_NAME'Access,
      UGRAVE_NAME'Access,
      UPSILON_NAME'Access,
      UUML_NAME'Access,
      XI_NAME'Access,
      YACUTE_NAME'Access,
      YUML_NAME'Access,
      ZETA_NAME'Access,
      N59_NAME'Access,
      N60_NAME'Access,
      ACUTE_NAME'Access,
      N62_NAME'Access,
      N63_NAME'Access,
      ALEFSYM_NAME'Access,
      N65_NAME'Access,
      AMP_NAME'Access,
      AND_NAME'Access,
      ANG_NAME'Access,
      APOS_NAME'Access,
      N70_NAME'Access,
      ASYMP_NAME'Access,
      N72_NAME'Access,
      N73_NAME'Access,
      BDQUO_NAME'Access,
      N75_NAME'Access,
      BRVBAR_NAME'Access,
      BULL_NAME'Access,
      CAP_NAME'Access,
      N79_NAME'Access,
      CEDIL_NAME'Access,
      CENT_NAME'Access,
      N82_NAME'Access,
      CIRC_NAME'Access,
      CLUBS_NAME'Access,
      CONG_NAME'Access,
      COPY_NAME'Access,
      CRARR_NAME'Access,
      CUP_NAME'Access,
      CURREN_NAME'Access,
      DARR_NAME'Access,
      N91_NAME'Access,
      N92_NAME'Access,
      DEG_NAME'Access,
      N94_NAME'Access,
      DIAMS_NAME'Access,
      DIVIDE_NAME'Access,
      N97_NAME'Access,
      N98_NAME'Access,
      N99_NAME'Access,
      EMPTY_NAME'Access,
      EMSP_NAME'Access,
      ENSP_NAME'Access,
      N103_NAME'Access,
      EQUIV_NAME'Access,
      N105_NAME'Access,
      N106_NAME'Access,
      N107_NAME'Access,
      EURO_NAME'Access,
      EXIST_NAME'Access,
      FNOF_NAME'Access,
      FORALL_NAME'Access,
      FRAC12_NAME'Access,
      FRAC14_NAME'Access,
      FRAC34_NAME'Access,
      FRASL_NAME'Access,
      N116_NAME'Access,
      GE_NAME'Access,
      GT_NAME'Access,
      HARR_NAME'Access,
      N120_NAME'Access,
      HEARTS_NAME'Access,
      HELLIP_NAME'Access,
      N123_NAME'Access,
      N124_NAME'Access,
      IEXCL_NAME'Access,
      N126_NAME'Access,
      IMAGE_NAME'Access,
      INFIN_NAME'Access,
      INT_NAME'Access,
      N130_NAME'Access,
      IQUEST_NAME'Access,
      ISIN_NAME'Access,
      N133_NAME'Access,
      N134_NAME'Access,
      LARR_NAME'Access,
      N136_NAME'Access,
      LANG_NAME'Access,
      LAQUO_NAME'Access,
      N139_NAME'Access,
      LCEIL_NAME'Access,
      LDQUO_NAME'Access,
      LE_NAME'Access,
      LFLOOR_NAME'Access,
      LOWAST_NAME'Access,
      LOZ_NAME'Access,
      LRM_NAME'Access,
      LSAQUO_NAME'Access,
      LSQUO_NAME'Access,
      LT_NAME'Access,
      MACR_NAME'Access,
      MDASH_NAME'Access,
      MICRO_NAME'Access,
      MIDDOT_NAME'Access,
      MINUS_NAME'Access,
      N155_NAME'Access,
      NABLA_NAME'Access,
      NBSP_NAME'Access,
      NDASH_NAME'Access,
      NE_NAME'Access,
      NI_NAME'Access,
      NOT_NAME'Access,
      NOTIN_NAME'Access,
      NSUB_NAME'Access,
      N164_NAME'Access,
      N165_NAME'Access,
      N166_NAME'Access,
      N167_NAME'Access,
      N168_NAME'Access,
      N169_NAME'Access,
      OLINE_NAME'Access,
      N171_NAME'Access,
      N172_NAME'Access,
      OPLUS_NAME'Access,
      OR_NAME'Access,
      ORDF_NAME'Access,
      ORDM_NAME'Access,
      N177_NAME'Access,
      N178_NAME'Access,
      OTIMES_NAME'Access,
      N180_NAME'Access,
      PARA_NAME'Access,
      PART_NAME'Access,
      PERMIL_NAME'Access,
      PERP_NAME'Access,
      N185_NAME'Access,
      N186_NAME'Access,
      PIV_NAME'Access,
      PLUSMN_NAME'Access,
      POUND_NAME'Access,
      N190_NAME'Access,
      PROD_NAME'Access,
      PROP_NAME'Access,
      N193_NAME'Access,
      QUOT_NAME'Access,
      RARR_NAME'Access,
      RADIC_NAME'Access,
      RANG_NAME'Access,
      RAQUO_NAME'Access,
      N199_NAME'Access,
      RCEIL_NAME'Access,
      RDQUO_NAME'Access,
      REAL_NAME'Access,
      REG_NAME'Access,
      RFLOOR_NAME'Access,
      N205_NAME'Access,
      RLM_NAME'Access,
      RSAQUO_NAME'Access,
      RSQUO_NAME'Access,
      SBQUO_NAME'Access,
      N210_NAME'Access,
      SDOT_NAME'Access,
      SECT_NAME'Access,
      SHY_NAME'Access,
      N214_NAME'Access,
      SIGMAF_NAME'Access,
      SIM_NAME'Access,
      SPADES_NAME'Access,
      SUB_NAME'Access,
      SUBE_NAME'Access,
      SUM_NAME'Access,
      SUP_NAME'Access,
      SUP1_NAME'Access,
      SUP2_NAME'Access,
      SUP3_NAME'Access,
      SUPE_NAME'Access,
      SZLIG_NAME'Access,
      N227_NAME'Access,
      THERE4_NAME'Access,
      N229_NAME'Access,
      THETASYM_NAME'Access,
      THINSP_NAME'Access,
      N232_NAME'Access,
      TILDE_NAME'Access,
      TIMES_NAME'Access,
      TRADE_NAME'Access,
      UARR_NAME'Access,
      N237_NAME'Access,
      N238_NAME'Access,
      N239_NAME'Access,
      N240_NAME'Access,
      UML_NAME'Access,
      UPSIH_NAME'Access,
      N243_NAME'Access,
      N244_NAME'Access,
      WEIERP_NAME'Access,
      N246_NAME'Access,
      N247_NAME'Access,
      YEN_NAME'Access,
      N249_NAME'Access,
      N250_NAME'Access,
      ZWJ_NAME'Access,
      ZWNJ_NAME'Access);

   Mapping : constant Char_Array := (
      Wide_Wide_Character'Val (198),
      Wide_Wide_Character'Val (193),
      Wide_Wide_Character'Val (194),
      Wide_Wide_Character'Val (192),
      Wide_Wide_Character'Val (913),
      Wide_Wide_Character'Val (197),
      Wide_Wide_Character'Val (195),
      Wide_Wide_Character'Val (196),
      Wide_Wide_Character'Val (914),
      Wide_Wide_Character'Val (199),
      Wide_Wide_Character'Val (935),
      Wide_Wide_Character'Val (8225),
      Wide_Wide_Character'Val (916),
      Wide_Wide_Character'Val (208),
      Wide_Wide_Character'Val (201),
      Wide_Wide_Character'Val (202),
      Wide_Wide_Character'Val (200),
      Wide_Wide_Character'Val (917),
      Wide_Wide_Character'Val (919),
      Wide_Wide_Character'Val (203),
      Wide_Wide_Character'Val (915),
      Wide_Wide_Character'Val (205),
      Wide_Wide_Character'Val (206),
      Wide_Wide_Character'Val (204),
      Wide_Wide_Character'Val (921),
      Wide_Wide_Character'Val (207),
      Wide_Wide_Character'Val (922),
      Wide_Wide_Character'Val (923),
      Wide_Wide_Character'Val (924),
      Wide_Wide_Character'Val (209),
      Wide_Wide_Character'Val (925),
      Wide_Wide_Character'Val (338),
      Wide_Wide_Character'Val (211),
      Wide_Wide_Character'Val (212),
      Wide_Wide_Character'Val (210),
      Wide_Wide_Character'Val (937),
      Wide_Wide_Character'Val (927),
      Wide_Wide_Character'Val (216),
      Wide_Wide_Character'Val (213),
      Wide_Wide_Character'Val (214),
      Wide_Wide_Character'Val (934),
      Wide_Wide_Character'Val (928),
      Wide_Wide_Character'Val (8243),
      Wide_Wide_Character'Val (936),
      Wide_Wide_Character'Val (929),
      Wide_Wide_Character'Val (352),
      Wide_Wide_Character'Val (931),
      Wide_Wide_Character'Val (222),
      Wide_Wide_Character'Val (932),
      Wide_Wide_Character'Val (920),
      Wide_Wide_Character'Val (218),
      Wide_Wide_Character'Val (219),
      Wide_Wide_Character'Val (217),
      Wide_Wide_Character'Val (933),
      Wide_Wide_Character'Val (220),
      Wide_Wide_Character'Val (926),
      Wide_Wide_Character'Val (221),
      Wide_Wide_Character'Val (376),
      Wide_Wide_Character'Val (918),
      Wide_Wide_Character'Val (225),
      Wide_Wide_Character'Val (226),
      Wide_Wide_Character'Val (180),
      Wide_Wide_Character'Val (230),
      Wide_Wide_Character'Val (224),
      Wide_Wide_Character'Val (8501),
      Wide_Wide_Character'Val (945),
      Wide_Wide_Character'Val (38),
      Wide_Wide_Character'Val (8743),
      Wide_Wide_Character'Val (8736),
      Wide_Wide_Character'Val (39),
      Wide_Wide_Character'Val (229),
      Wide_Wide_Character'Val (8776),
      Wide_Wide_Character'Val (227),
      Wide_Wide_Character'Val (228),
      Wide_Wide_Character'Val (8222),
      Wide_Wide_Character'Val (946),
      Wide_Wide_Character'Val (166),
      Wide_Wide_Character'Val (8226),
      Wide_Wide_Character'Val (8745),
      Wide_Wide_Character'Val (231),
      Wide_Wide_Character'Val (184),
      Wide_Wide_Character'Val (162),
      Wide_Wide_Character'Val (967),
      Wide_Wide_Character'Val (710),
      Wide_Wide_Character'Val (9827),
      Wide_Wide_Character'Val (8773),
      Wide_Wide_Character'Val (169),
      Wide_Wide_Character'Val (8629),
      Wide_Wide_Character'Val (8746),
      Wide_Wide_Character'Val (164),
      Wide_Wide_Character'Val (8659),
      Wide_Wide_Character'Val (8224),
      Wide_Wide_Character'Val (8595),
      Wide_Wide_Character'Val (176),
      Wide_Wide_Character'Val (948),
      Wide_Wide_Character'Val (9830),
      Wide_Wide_Character'Val (247),
      Wide_Wide_Character'Val (233),
      Wide_Wide_Character'Val (234),
      Wide_Wide_Character'Val (232),
      Wide_Wide_Character'Val (8709),
      Wide_Wide_Character'Val (8195),
      Wide_Wide_Character'Val (8194),
      Wide_Wide_Character'Val (949),
      Wide_Wide_Character'Val (8801),
      Wide_Wide_Character'Val (951),
      Wide_Wide_Character'Val (240),
      Wide_Wide_Character'Val (235),
      Wide_Wide_Character'Val (8364),
      Wide_Wide_Character'Val (8707),
      Wide_Wide_Character'Val (402),
      Wide_Wide_Character'Val (8704),
      Wide_Wide_Character'Val (189),
      Wide_Wide_Character'Val (188),
      Wide_Wide_Character'Val (190),
      Wide_Wide_Character'Val (8260),
      Wide_Wide_Character'Val (947),
      Wide_Wide_Character'Val (8805),
      Wide_Wide_Character'Val (62),
      Wide_Wide_Character'Val (8660),
      Wide_Wide_Character'Val (8596),
      Wide_Wide_Character'Val (9829),
      Wide_Wide_Character'Val (8230),
      Wide_Wide_Character'Val (237),
      Wide_Wide_Character'Val (238),
      Wide_Wide_Character'Val (161),
      Wide_Wide_Character'Val (236),
      Wide_Wide_Character'Val (8465),
      Wide_Wide_Character'Val (8734),
      Wide_Wide_Character'Val (8747),
      Wide_Wide_Character'Val (953),
      Wide_Wide_Character'Val (191),
      Wide_Wide_Character'Val (8712),
      Wide_Wide_Character'Val (239),
      Wide_Wide_Character'Val (954),
      Wide_Wide_Character'Val (8656),
      Wide_Wide_Character'Val (955),
      Wide_Wide_Character'Val (9001),
      Wide_Wide_Character'Val (171),
      Wide_Wide_Character'Val (8592),
      Wide_Wide_Character'Val (8968),
      Wide_Wide_Character'Val (8220),
      Wide_Wide_Character'Val (8804),
      Wide_Wide_Character'Val (8970),
      Wide_Wide_Character'Val (8727),
      Wide_Wide_Character'Val (9674),
      Wide_Wide_Character'Val (8206),
      Wide_Wide_Character'Val (8249),
      Wide_Wide_Character'Val (8216),
      Wide_Wide_Character'Val (60),
      Wide_Wide_Character'Val (175),
      Wide_Wide_Character'Val (8212),
      Wide_Wide_Character'Val (181),
      Wide_Wide_Character'Val (183),
      Wide_Wide_Character'Val (8722),
      Wide_Wide_Character'Val (956),
      Wide_Wide_Character'Val (8711),
      Wide_Wide_Character'Val (160),
      Wide_Wide_Character'Val (8211),
      Wide_Wide_Character'Val (8800),
      Wide_Wide_Character'Val (8715),
      Wide_Wide_Character'Val (172),
      Wide_Wide_Character'Val (8713),
      Wide_Wide_Character'Val (8836),
      Wide_Wide_Character'Val (241),
      Wide_Wide_Character'Val (957),
      Wide_Wide_Character'Val (243),
      Wide_Wide_Character'Val (244),
      Wide_Wide_Character'Val (339),
      Wide_Wide_Character'Val (242),
      Wide_Wide_Character'Val (8254),
      Wide_Wide_Character'Val (969),
      Wide_Wide_Character'Val (959),
      Wide_Wide_Character'Val (8853),
      Wide_Wide_Character'Val (8744),
      Wide_Wide_Character'Val (170),
      Wide_Wide_Character'Val (186),
      Wide_Wide_Character'Val (248),
      Wide_Wide_Character'Val (245),
      Wide_Wide_Character'Val (8855),
      Wide_Wide_Character'Val (246),
      Wide_Wide_Character'Val (182),
      Wide_Wide_Character'Val (8706),
      Wide_Wide_Character'Val (8240),
      Wide_Wide_Character'Val (8869),
      Wide_Wide_Character'Val (966),
      Wide_Wide_Character'Val (960),
      Wide_Wide_Character'Val (982),
      Wide_Wide_Character'Val (177),
      Wide_Wide_Character'Val (163),
      Wide_Wide_Character'Val (8242),
      Wide_Wide_Character'Val (8719),
      Wide_Wide_Character'Val (8733),
      Wide_Wide_Character'Val (968),
      Wide_Wide_Character'Val (34),
      Wide_Wide_Character'Val (8658),
      Wide_Wide_Character'Val (8730),
      Wide_Wide_Character'Val (9002),
      Wide_Wide_Character'Val (187),
      Wide_Wide_Character'Val (8594),
      Wide_Wide_Character'Val (8969),
      Wide_Wide_Character'Val (8221),
      Wide_Wide_Character'Val (8476),
      Wide_Wide_Character'Val (174),
      Wide_Wide_Character'Val (8971),
      Wide_Wide_Character'Val (961),
      Wide_Wide_Character'Val (8207),
      Wide_Wide_Character'Val (8250),
      Wide_Wide_Character'Val (8217),
      Wide_Wide_Character'Val (8218),
      Wide_Wide_Character'Val (353),
      Wide_Wide_Character'Val (8901),
      Wide_Wide_Character'Val (167),
      Wide_Wide_Character'Val (173),
      Wide_Wide_Character'Val (963),
      Wide_Wide_Character'Val (962),
      Wide_Wide_Character'Val (8764),
      Wide_Wide_Character'Val (9824),
      Wide_Wide_Character'Val (8834),
      Wide_Wide_Character'Val (8838),
      Wide_Wide_Character'Val (8721),
      Wide_Wide_Character'Val (8835),
      Wide_Wide_Character'Val (185),
      Wide_Wide_Character'Val (178),
      Wide_Wide_Character'Val (179),
      Wide_Wide_Character'Val (8839),
      Wide_Wide_Character'Val (223),
      Wide_Wide_Character'Val (964),
      Wide_Wide_Character'Val (8756),
      Wide_Wide_Character'Val (952),
      Wide_Wide_Character'Val (977),
      Wide_Wide_Character'Val (8201),
      Wide_Wide_Character'Val (254),
      Wide_Wide_Character'Val (732),
      Wide_Wide_Character'Val (215),
      Wide_Wide_Character'Val (8482),
      Wide_Wide_Character'Val (8657),
      Wide_Wide_Character'Val (250),
      Wide_Wide_Character'Val (8593),
      Wide_Wide_Character'Val (251),
      Wide_Wide_Character'Val (249),
      Wide_Wide_Character'Val (168),
      Wide_Wide_Character'Val (978),
      Wide_Wide_Character'Val (965),
      Wide_Wide_Character'Val (252),
      Wide_Wide_Character'Val (8472),
      Wide_Wide_Character'Val (958),
      Wide_Wide_Character'Val (253),
      Wide_Wide_Character'Val (165),
      Wide_Wide_Character'Val (255),
      Wide_Wide_Character'Val (950),
      Wide_Wide_Character'Val (8205),
      Wide_Wide_Character'Val (8204));
end Wiki.Parsers.Html.Entities;
